<?php

/**
 * @file
 * Contains todo_new.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function todo_new_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the todo_new module.
    case 'help.page.todo_new':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Todo New Module') . '</p>';
      return $output;

    default:
  }
}
